### ISSUE TITLE
A mistake on week 7 note

### ISSUE THREAD

**Issue by ashhher** [ssswww4444/IML2021S2-Tutorial#1]
Hi, Pei Yun:
There is a mistake in the answer of Q7.  For the first epoch, the inputs should be <p0, p1, p2>, the header is right but the values are the <x0, x1, x2> values. 
<img width="657" alt="fd3245c6f35059574a34f4fc9814d6a" src="https://user-images.githubusercontent.com/61083392/133221821-68d54c79-c943-408f-91ec-681d0aabfd9a.png">
<img width="143" alt="32882dbf329c7a43a85d25110dc3f6a" src="https://user-images.githubusercontent.com/61083392/133221834-abaf02a3-6a27-4220-9767-8223b464d2db.png">
Regards,
Han.

**Comment by ssswww4444** [comment]
That's right. Thanks for pointing it out!
I've just uploaded the correct one.
